---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: busybox-drpc
  labels:
    app: busybox-sample
spec:
  preferredCluster: "PLACEHOLDER-C1-ClusterName"
  drPolicyRef:
    name: PLACEHOLDER-DRPOLICY-NAME
  placementRef:
    kind: Placement
    name: busybox-1-placement
  pvcSelector:
    matchLabels:
      appname: busybox_app1
