---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: busybox-1-placement
  namespace: busybox-workloads-1 
  labels:
    app: busybox-sample
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'name'
              operator: 'In'
              values:
                - PLACEHOLDER
  clusterSets:
    - global
