apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox_app_mix
  name: busybox-pvc-mix-cephfs-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 94Gi
  storageClassName: ocs-storagecluster-cephfs
