apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox_app_mix
  name: busybox-pvc-mix-rbd-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 94Gi
  storageClassName: ocs-storagecluster-ceph-rbd
